version: "2.2"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
